[default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 3
optimizer_details.yul = true
optimizer_details.yul_details.stack_allocation = true
fuzz_runs = 5
fuzz_max_global_rejects = 131072

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
